allow-uncaught: false
ui: 'bdd'
timeout: 0
full-trace: true
color: true
inline-diffs: true
async-only: true
parallel: false
jobs: 10
recursive: false
diff: true
retries: 0
spec:
  - 'test/**/*.spec.js'
extension:
  - js
