export const ORDER_STATUS_STEP_MAP = {
  QUOTE: 0,
  SECRET_READY: 0,
  INITIATED: 0,
  INITIATION_REPORTED: 0,
  INITIATION_CONFIRMED: 1,
  CONFIRM_COUNTER_PARTY_INITIATION: 1,
  READY_TO_CLAIM: 2,
  WAITING_FOR_CLAIM_CONFIRMATIONS: 2,
  GET_REFUND: 2,
  WAITING_FOR_REFUND_CONFIRMATIONS: 2,
  REFUNDED: 3,
  SUCCESS: 3,
  READY_TO_SEND: 3
}

export const ORDER_STATUS_LABEL_MAP = {
  QUOTE: 'Initiating',
  SECRET_READY: 'Initiating',
  INITIATED: 'Initiating',
  INITIATION_REPORTED: 'Initiating',
  INITIATION_CONFIRMED: 'Pending Agent',
  CONFIRM_COUNTER_PARTY_INITIATION: 'Pending Agent',
  READY_TO_CLAIM: 'Claiming',
  WAITING_FOR_CLAIM_CONFIRMATIONS: 'Claiming',
  GET_REFUND: 'Refunding',
  WAITING_FOR_REFUND_CONFIRMATIONS: 'Refunding',
  REFUNDED: 'Refunded',
  SUCCESS: 'Completed',
  READY_TO_SEND: 'Sending'
}
