on:
  schedule:
    - cron: '0 8 * * *' # everyday at 8am
    - cron: '0 22 * * *' # everyday at 10pm

#Dev testnet tests
name: Testnet tests

jobs:
  regressiontest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2.5.0
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: '14'
      # Create screenshots directory
      - run: mkdir screenshots

      - uses: actions/cache@v2.1.7
        env:
          node-version: 14.1.0
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: Set development manifest
        run: |
          echo VUE_APP_AMPLITUDE_API_KEY =${{ secrets.VUE_APP_AMPLITUDE_API_KEY_DEV }} >> .env
          jq --argjson icons "{\"16\": \"icons/dev/16x16.png\",\"48\": \"icons/dev/48x48.png\",\"128\": \"icons/dev/128x128.png\"}" '.icons = $icons | .browser_action.default_icon = $icons | .name = "Liquality Wallet - Dev"' ./src/manifest.json > ./src/manifest.tmp
          mv ./src/manifest.tmp ./src/manifest.json
          npm ci
          npm run lint
          npm run build

      - name: Regression tests against Testnet
        uses: beemi/puppeteer-headful@v1.0.6
        env:
          CI: 'true'
          DISPLAY: :99
          SEED_WORDS: ${{ secrets.TEST_NET_SEED_WORDS }}
          TWENTY_FOUR_SEEDS: ${{ secrets.TWENTY_FOUR_SEEDS }}
        with:
          args: npm run test:testnet

#      - name: Archive Mocha HTML report
#        uses: actions/upload-artifact@v2.2.4
#        if: always()
#        with:
#          name: mocha-html-test-report
#          path: mochawesome-report

      - name: Save Screenshots
        uses: actions/upload-artifact@v2.3.0
        if: always()
        with:
          name: screenshots
          path: screenshots
          if-no-files-found: ignore



